### PR TITLE
Add unit test for reconnecting a client

### PR DESCRIPTION
**Pull request by pasnox**
Task-Id: KDEND-199

### CODE REVIEW

**Comment by pasnox** [comment]
Fixed

**Comment by vkrause** [comment]
Seems only to be fixed for the two 5.9 OSX configurations, the rest is still failing, no?

**Comment by pasnox** [comment]
Everything is green here  ??

**Comment by pasnox** [comment]
All fixed, QProcess behavior difference between windows vs the world for console application.

**Pull request merged**
