### PR TITLE
CMake: Allow to disable Qt5::Script dependency

### LINKED ISSUE #492: scriptenginedebugger.h:34:10: fatal error: QScriptEngine: No such file or directory
I am getting the above error every time I compile without qtscript enabled 
(i.e. `-DCMAKE_DISABLE_FIND_PACKAGE_Qt5Script=ON` in the ebuild).
```
[ 58%] Building CXX object plugins/scriptenginedebugger/CMakeFiles/gammaray_scriptenginedebugger_plugin.dir/scriptenginedebugger.cpp.o
cd /tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build/plugins/scriptenginedebugger && /usr/bin/x86_64-pc-linux-gnu-g++ -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_URL_CAST_FROM_STRING -DQT_SCRIPTTOOLS_LIB -DQT_STRICT_ITERATORS -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -Dgammaray_scriptenginedebugger_plugin_EXPORTS -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build/plugins/scriptenginedebugger -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0/plugins/scriptenginedebugger -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build/plugins/scriptenginedebugger/gammaray_scriptenginedebugger_plugin_autogen/include -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0 -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0/3rdparty -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtScriptTools -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build/core -I/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0_build/common   -DNDEBUG -march=native  -frecord-gcc-switches  -flto=5 -flto-report -fuse-linker-plugin  -pipe -O2 -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wformat-security -Wno-c++1z-extensions -Wall -Wextra -pedantic -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -fno-operator-names -Wzero-as-null-pointer-constant -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/gammaray_scriptenginedebugger_plugin.dir/scriptenginedebugger.cpp.o -c /tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0/plugins/scriptenginedebugger/scriptenginedebugger.cpp
In file included from /tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0/plugins/scriptenginedebugger/scriptenginedebugger.cpp:29:0:
/tmp/portage/dev-util/gammaray-2.9.0/work/gammaray-2.9.0/plugins/scriptenginedebugger/scriptenginedebugger.h:34:10: fatal error: QScriptEngine: No such file or directory
 #include <QScriptEngine>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

When I enable the script USE flag (`-DCMAKE_DISABLE_FIND_PACKAGE_Qt5Script=OFF`) no error occurs.

I found a workaround, if script is disabled a `sed` removes `add_subdirectory(scriptenginedebugger)` line from plugins/CMakeLists.txt in the ebuild.
```
if use !script ; then
	sed -i "/add_subdirectory(scriptenginedebugger)/d" plugins/CMakeLists.txt || die
fi
```
This is not the case for other config options, so am I missing another config option, or it's a bug in the CMakeLists?

### PR DESCRIPTION
**Pull request by krf**
... and in that case make sure the scriptenginedebugger plugin isn't
built

Fixes #492

### CODE REVIEW

**Comment by krf** [comment]
@petross404: Does this fix your issue?

**Comment by Petross404** [comment]
@krf ~~I think portage didn't pull the latest changes. For some reason I didn't see the `plugins/CMakeLists.txt` to have any + or - when I reinstalled gammaray. It seems it's not changed.~~

I noticed the commit is push to your forked repo. It will take some time to make the ebuild sync with yours, download it and test the results.

**Comment by Petross404** [comment]
It's a yes, emerging from your branch without `script` use flag and the sed workaround was successful.

**Comment by Petross404** [comment]
Hmm, I see that it isn't merged to master branch which is what portage by default pulls. Anyway I will just use this [patch](https://github.com/KDAB/GammaRay/commit/3c705e016746a838add37715b97a6e7dd43bf846.patch).

**Pull request merged**
