### PR TITLE
RemoteModel: Fix deleted child access

### LINKED ISSUE #672: Crash in Node deallocation
### Summary

GammaRay may crash when a big set of objects is changing with inspected application. In my case it was a Plasma applet's configuration containment, and I switched config sections on the left while inspecting object tree of current section.

coredumpctl gdb and backtrace: https://gist.github.com/ratijas/0810d8b51cdd0ecc7f48cc846a67941f

### Steps to reproduce

1. Launch executable from GammaRay:
	- Executable: /usr/bin/plasmoidviewer
	- Arguments: `["-a", "org.kde.plasma.timer"]`
	- Access mode: Out of process, local-only
	Launch options
 2. Press & hold on applet to enter Edit mode.
 3. Click «Configure Timer…» button on the overlay that appears besides the applet
	 Configure button
 4. Switch configuration sections from an initial «Appearance» to «Predefined Timers».
	Configuration sections

### Observed result

GammaRay silently crashes, leaving Plasmoid Viewer process intact.

### Version

Operating System: Arch Linux
KDE Plasma Version: 5.24.80 (but actually built from git master)
KDE Frameworks Version: 5.91.0 (but actually built from git master)
Qt Version: 5.15.2+kde+r294-1
Kernel Version: 5.16.2-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970M/PCIe/SSE2

GammaRay: 2.11.3-1

### PR DESCRIPTION
**Pull request by Waqar144**
If there are > 1 nodes in the list such as:

[node1, childOfNode1]

it crashes, because by the time we reach 2nd item, it is already deleted
because of its relation with the first. Remove such nodes before
iterating.

Fixes #672

### CODE REVIEW

**Comment by ratijas** [comment]
Thanks!
Can confirm that this patch fixes consistent crash on startup when attaching to plasmashell.

**Comment by ratijas** [comment]
However, there's now (or still?) another segfault in `RemoteModel::Node::hasColumnData()`:

```
Core was generated by `/home/ratijas/kde/usr/lib/gammaray/libexec/gammaray-client tcp://127.0.0.1:1173'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3c2ae52b88 in GammaRay::RemoteModel::Node::hasColumnData() const () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_client.so.3.0.0
[Current thread is 1 (Thread 0x7f3c25e62840 (LWP 214611))]
(gdb) bt
#0  0x00007f3c2ae52b88 in GammaRay::RemoteModel::Node::hasColumnData() const () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_client.so.3.0.0
#1  0x00007f3c2ae52ead in GammaRay::RemoteModel::flags(QModelIndex const&) const () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_client.so.3.0.0
#2  0x00007f3c29df8f7d in QAbstractProxyModel::flags(QModelIndex const&) const () from /usr/lib/libQt5Core.so.5
#3  0x00007f3c2ab67e86 in QTreeView::isExpanded(QModelIndex const&) const () from /usr/lib/libQt5Widgets.so.5
#4  0x00007f3c2ab78794 in QTreeView::verticalScrollbarValueChanged(int) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007f3c29e5addf in ?? () from /usr/lib/libQt5Core.so.5
#6  0x00007f3c2a980e63 in QAbstractSlider::valueChanged(int) () from /usr/lib/libQt5Widgets.so.5
#7  0x00007f3c2a981fde in QAbstractSlider::setValue(int) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007f3c2ab78136 in QTreeViewPrivate::updateScrollBars() () from /usr/lib/libQt5Widgets.so.5
#9  0x00007f3c2ab783ab in QTreeView::updateGeometries() () from /usr/lib/libQt5Widgets.so.5
#10 0x00007f3c2ab730d7 in QTreeView::columnCountChanged(int, int) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007f3c29e5addf in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007f3c2ab19c84 in QHeaderView::sectionCountChanged(int, int) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007f3c2ac3dbbf in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f3c29e5addf in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007f3c29de6fab in QAbstractItemModel::layoutChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) () from /usr/lib/libQt5Core.so.5
#16 0x00007f3c29e01c00 in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007f3c29e5addf in ?? () from /usr/lib/libQt5Core.so.5
#18 0x00007f3c29de6fab in QAbstractItemModel::layoutChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) () from /usr/lib/libQt5Core.so.5
#19 0x00007f3c2ae5b390 in GammaRay::RemoteModel::newMessage(GammaRay::Message const&) () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_client.so.3.0.0
#20 0x00007f3c29e386ab in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () from /usr/lib/libQt5Core.so.5
#21 0x00007f3c2ae0c922 in GammaRay::Endpoint::dispatchMessage(GammaRay::Message const&) () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_common-qt5_15-x86_64.so.3.0.0
#22 0x00007f3c2ae09080 in GammaRay::Endpoint::readyRead() () from /home/ratijas/kde/usr/lib/gammaray/libexec/../../libgammaray_common-qt5_15-x86_64.so.3.0.0
#23 0x00007f3c29e5ad93 in ?? () from /usr/lib/libQt5Core.so.5
#24 0x00007f3c29354130 in ?? () from /usr/lib/libQt5Network.so.5
#25 0x00007f3c2936aa0a in ?? () from /usr/lib/libQt5Network.so.5
#26 0x00007f3c2a89c1a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#27 0x00007f3c29e2a16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#28 0x00007f3c29e74276 in ?? () from /usr/lib/libQt5Core.so.5
#29 0x00007f3c287f5f13 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#30 0x00007f3c2884c0d9 in ?? () from /usr/lib/libglib-2.0.so.0
#31 0x00007f3c287f3485 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#32 0x00007f3c29e7544a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#33 0x00007f3c29e2244b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#34 0x00007f3c29e2db97 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#35 0x000055f40664d6e5 in main ()
```

**Comment by Waqar144** [comment]
> However, there's now (or still?) another segfault in `RemoteModel::Node::hasColumnData()`:
> 
> ```
> Core was generated by `/home/ratijas/kde/usr/lib/gammaray/libexec/gammaray-client tcp://127.0.0.1:1173'.
> Program terminated with signal SIGSEGV, Segmentation fault.....
> ```

Can you check if it crashes without this patch? If it doesn't, can you open another issue with details on how to reproduce?

**Comment by ratijas** [comment]
> Can you check if it crashes without this patch? If it doesn't, can you open another issue with details on how to reproduce?

Sorry, I'm afraid it's not possible. It was just so random, and I was already so sleepy and tired that I already forgot how was it triggered… My only hope, when reporting, was that the bug would be obvious for someone who is familiar with code :)

**Review by vkrause — APPROVED** [review]
Makes sense to me.

**Pull request merged**
