### PR TITLE
Delete cached widgets

### PR DESCRIPTION
**Pull request by bog-dan-ro**

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
Isn't gammaray supposed to be built with pre c++11 ?

**Comment by bog-dan-ro** [comment]
auto version + moved the clear code to a separate function.

**Comment by krf** [comment]
:+1: -- can you push to 2.4?

**Comment by bog-dan-ro** [comment]
https://github.com/KDAB/GammaRay/pull/179

**Pull request closed without merging**
