### PR TITLE
Launcher page: explain why the error button is disabled

### PR DESCRIPTION
**Pull request by tsdgeos**
Sometimes is not trivial to realize that the ABI for the binary you're trying to launch is not available

### CODE REVIEW

**Comment by tsdgeos** [comment]
I'm actually shocked you closed this, oh well

**Comment by dantti** [comment]
LGTM @Waqar144 I guess it was a mistake? or are you addressing this in another way?

**Comment by tsdgeos** [comment]
I guess this was closed because i didn't sign the CLA [yet], and I accept it's fine to get bored waiting for it, but if that's the reason for closing it, at least please say so.

**Comment by Waqar144** [comment]
Sorry, didn't mean it like that. Yeah it was because of the CLA thingy, should have asked you first, my bad.

**Comment by Waqar144** [comment]
Thanks! :)

**Pull request merged**
