### PR TITLE
Feature: Ctrl+LeftClick Drag panning for non-pan tools

### LINKED ISSUE #933: Quick Scenes: always pan view with <modifier>+click
Currently one has to switch to the pan view tool then click and drag to move the preview of the app.
It would be nice, if regardless of the tool selected, one could just hold a modifier key + left/right click to move the preview.

### PR DESCRIPTION
**Pull request by mattkdab**
Requested feature.

Enable Ctrl+Shift+LeftClick Dragging to pan the remote view when using interaction modes other than ViewInteraction.

Should close #933

### CODE REVIEW

**Comment by mattkdab** [comment]
just noticed #741 is sort of the same as this?

**Comment by g-fb** [comment]
Any reason for requiring both Ctrl and Shift to be pressed?

Anyway, thank you for adding this.

**Comment by mattkdab** [comment]
> Any reason for requiring both Ctrl and Shift to be pressed?
> 
> Anyway, thank you for adding this.

Hm, right I suppose it _could_ just be Ctrl, since this is only when not using the pan tool (Ctrl clicking with pan tool performs a Pick Element). I'll update with that change.

**Comment by Waqar144** [comment]
related https://github.com/KDAB/GammaRay/pull/741

**Review by Waqar144 — APPROVED** [review]

**Comment by winterz** [comment]
@mattkdab I'm stumped why the cla-assistant doesn't recognize you.  I'll approve this and merge.

**Review by winterz — APPROVED** [review]

**Pull request merged**
