### PR TITLE
Add "Copy backtrace" to message dialog

### PR DESCRIPTION
**Pull request by agabor**
implementation of issue #25

I have seen that this issue have been abandoned for quite a while, so I took the courage and implemented it. Please review my changes!

### CODE REVIEW

**Comment by krf** [comment]
Code looks good. Did you test it?

Unfortunately I'm not sure *how* to test it. GammaRay changed quite a bit, and currently the message dialog is covered by the "Lost connection to remote host: The remote host closed the connection" dialog as soon as a `qFatal(...)` was registered...

**Comment by agabor** [comment]
Yes I have also realized that, and I wasn't sure if thats intentional. But yes I have tested it, open the messages tab first, then cause a qFatal in the host and then the dialog will appear.

**Comment by krf** [comment]
Merging this, code looks fine to me. 

We need to make sure the dialog isn't covered by the other dialog, though. Which is a different issue. Maybe you'd like look into that as well?

Thanks for the patch!

**Comment by agabor** [comment]
Seems like `MessageHandlerWidget` is only created whe the "Messages" tab is first opened, otherwise the `fatalMessageReceived` signal does not get handled. I will look into this. (In two weeks at least, I am having a hollyday.)

Thank you for the feedback!

**Pull request merged**
