### PR TITLE
Qt 6.7 temp fix, change to Qt needed to fully fix

### LINKED ISSUE #918: Building against Qt 6.7 fails
Steps to reproduce:

1. install Qt 6.7
2. `git clone https://github.com/KDAB/GammaRay.git`
3. `mkdir build && cd build`
4. `cmake -G Ninja -DQT_VERSION_MAJOR=6 ..`
5. `cmake -build .`

<details>
  <summary>Full output of failed command:</summary>

```
[1/1111] Automatic MOC and UIC for target test_helpers_obj
[2/1111] Automatic MOC and UIC for target gammaray_lz4
[3/1111] Automatic MOC and UIC for target modeltestobj
[4/1111] Building CXX object common/CMakeFiles/gammaray_lz4.dir/gammaray_lz4_autogen/mocs_compilation.cpp.o
[5/1111] Automatic MOC and UIC for target gammaray_probe_obj
[6/1111] Automatic MOC and UIC for target connectiontest
[7/1111] Automatic MOC and UIC for target gammaray_kitemmodels
[8/1111] Automatic MOC and UIC for target gammaray_injector_style
[9/1111] Automatic MOC and UIC for target gammaray_kuserfeedback
[10/1111] Automatic MOC and UIC for target base_quick_test_obj
[11/1111] Automatic MOC and UIC for target base_probe_test_obj
[12/1111] Building C object common/CMakeFiles/gammaray_lz4.dir/__/3rdparty/lz4/lz4.c.o
[13/1111] Linking CXX static library common/libgammaray_lz4.a
[14/1111] Building CXX object probe/CMakeFiles/gammaray_probe_obj.dir/gammaray_probe_obj_autogen/mocs_compilation.cpp.o
[15/1111] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/gammaray_kitemmodels_autogen/mocs_compilation.cpp.o
[16/1111] Building CXX object probe/CMakeFiles/gammaray_probe_obj.dir/entry_unix.cpp.o
[17/1111] Building CXX object probe/CMakeFiles/gammaray_probe_obj.dir/hooks.cpp.o
[18/1111] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/kitemmodels_debug.cpp.o
[19/1111] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/kmodelindexproxymapper.cpp.o
[20/1111] Building CXX object probe/CMakeFiles/gammaray_probe_obj.dir/probecreator.cpp.o
[21/1111] Building CXX object launcher/core/injector/CMakeFiles/gammaray_injector_style.dir/gammaray_injector_style_autogen/mocs_compilation.cpp.o
[22/1111] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/klinkitemselectionmodel.cpp.o
[23/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/common/surveytargetexpression.cpp.o
[24/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/gammaray_kuserfeedback_autogen/mocs_compilation.cpp.o
[25/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/common/surveytargetexpressionevaluator.cpp.o
[26/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/common/surveytargetexpressionlexer.cpp.o
[27/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/common/surveytargetexpressionparser.cpp.o
[28/1111] Building CXX object launcher/core/injector/CMakeFiles/gammaray_injector_style.dir/injectorstyleplugin.cpp.o
[29/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/abstractdatasource.cpp.o
[30/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/common/surveytargetexpressionparser_p.cpp.o
[31/1111] Linking CXX shared module lib/gammaray/3.0/qt6_7-x86_64/styles/gammaray_injector_style.so
[32/1111] Building CXX object 3rdparty/kde/CMakeFiles/gammaray_kitemmodels.dir/kdescendantsproxymodel.cpp.o
[33/1111] Linking CXX shared library lib/libgammaray_kitemmodels-qt6_7-x86_64.so.3.0.0
[34/1111] Creating library symlink lib/libgammaray_kitemmodels-qt6_7-x86_64.so
[35/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/applicationversionsource.cpp.o
[36/1111] Automatic MOC and UIC for target gammaray_common
[37/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/compilerinfosource.cpp.o
[38/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/openglinfosource.cpp.o
[39/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/platforminfosource.cpp.o
[40/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/commonutils.cpp.o
[41/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/qtversionsource.cpp.o
[42/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/classesiconsrepository.cpp.o
[43/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/feedbackconfiguicontroller.cpp.o
[44/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/selectionratiosource.cpp.o
[45/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/provider.cpp.o
[46/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/enumdefinition.cpp.o
[47/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/enumrepository.cpp.o
[48/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/enumvalue.cpp.o
[49/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/gammaray_common_autogen/mocs_compilation.cpp.o
[50/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/endpoint.cpp.o
[51/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/methodargument.cpp.o
[52/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/modelevent.cpp.o
[53/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/modelutils.cpp.o
[54/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/paintanalyzerinterface.cpp.o
[55/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/objectidfilterproxymodel.cpp.o
[56/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/objectbroker.cpp.o
[57/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/message.cpp.o
[58/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/propertysyncer.cpp.o
[59/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/protocol.cpp.o
[60/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/paths.cpp.o
[61/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/remoteviewframe.cpp.o
[62/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/selflocator.cpp.o
[63/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/transferimage.cpp.o
[64/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/sourcelocation.cpp.o
[65/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/startcountsource.cpp.o
[66/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/surveyinfo.cpp.o
[67/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/translator.cpp.o
[68/1111] Automatic MOC and UIC for target attachhelper
[69/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/usagetimesource.cpp.o
[70/1111] Building CXX object common/CMakeFiles/gammaray_common.dir/remoteviewinterface.cpp.o
[71/1111] Automatic MOC and UIC for target multisignalmappertest
[72/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/widgets/feedbackconfigdialog.cpp.o
[73/1111] Linking CXX shared library lib/libgammaray_common-qt6_7-x86_64.so.3.0.0
[74/1111] Creating library symlink lib/libgammaray_common-qt6_7-x86_64.so
[75/1111] Automatic MOC and UIC for target signalspycallbacktest
[76/1111] Automatic MOC and UIC for target problemreportertest
[77/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/widgets/notificationpopup.cpp.o
[78/1111] Automatic MOC and UIC for target integrationtest
[79/1111] Automatic MOC and UIC for target gammaray_common_internal
[80/1111] Automatic MOC and UIC for target gammaray_launcher
[81/1111] Automatic MOC and UIC for target sleep
[82/1111] Automatic MOC and UIC for target multithreadingtest
[83/1111] Automatic MOC and UIC for target methodmodeltest
[84/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/widgets/auditlogbrowserdialog.cpp.o
[85/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/widgets/feedbackconfigwidget.cpp.o
[86/1111] Building CXX object 3rdparty/kuserfeedback/CMakeFiles/gammaray_kuserfeedback.dir/core/auditloguicontroller.cpp.o
[87/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/favoriteobjectinterface.cpp.o
[88/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/propertycontrollerinterface.cpp.o
[89/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/networkselectionmodel.cpp.o
[90/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/plugininfo.cpp.o
[91/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/pluginmanager.cpp.o
[92/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/probecontrollerinterface.cpp.o
[93/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/gammaray_common_internal_autogen/mocs_compilation.cpp.o
[94/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/objectinspector/methodsextensioninterface.cpp.o
[95/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/metatypebrowser/metatypebrowserinterface.cpp.o
[96/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/messagehandler/messagehandlerinterface.cpp.o
[97/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/objectinspector/propertiesextensioninterface.cpp.o
[98/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/objectinspector/connectionsextensioninterface.cpp.o
[99/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/proxyfactorybase.cpp.o
[100/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/toolmanagerinterface.cpp.o
[101/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/streamoperators.cpp.o
[102/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/problemreporter/problemreporterinterface.cpp.o
[103/1111] Building CXX object common/CMakeFiles/gammaray_common_internal.dir/tools/resourcebrowser/resourcebrowserinterface.cpp.o
[104/1111] Linking CXX static library common/libgammaray_common_internal.a
[105/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/clientlauncher.cpp.o
[106/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/injectorfactory.cpp.o
[107/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/gammaray_launcher_autogen/mocs_compilation.cpp.o
[108/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/processinjector.cpp.o
[109/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/abstractinjector.cpp.o
[110/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/libraryutil.cpp.o
[111/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/styleinjector.cpp.o
[112/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/launcherfinder.cpp.o
[113/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/launcher.cpp.o
[114/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/launchoptions.cpp.o
[115/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/networkdiscoverymodel.cpp.o
[116/1111] Automatic MOC and UIC for target gammaray_core
[117/1111] Automatic RCC for ../resources/gammaray.qrc
[118/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/probeabi.cpp.o
[119/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/selftest.cpp.o
[120/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/probeabidetector.cpp.o
[121/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/gdbinjector.cpp.o
[122/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/probefinder.cpp.o
[123/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/lldbinjector.cpp.o
[124/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/abstractbindingprovider.cpp.o
[125/1111] Building CXX object launcher/core/CMakeFiles/gammaray_launcher.dir/injector/debuggerinjector.cpp.o
[126/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/attributemodel.cpp.o
[127/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/associativepropertyadaptor.cpp.o
[128/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/classesiconsrepositoryserver.cpp.o
[129/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/aggregatedpropertymodel.cpp.o
[130/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/__/3rdparty/qt/resourcemodel.cpp.o
[131/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/bindingaggregator.cpp.o
[132/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/bindingnode.cpp.o
[133/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/dynamicpropertyadaptor.cpp.o
[134/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/enumrepositoryserver.cpp.o
[135/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/enumutil.cpp.o
[136/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/favoriteobject.cpp.o
[137/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/execution.cpp.o
[138/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/jsonpropertyadaptor.cpp.o
[139/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/metaobject.cpp.o
[140/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/metaproperty.cpp.o
[141/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/metapropertyadaptor.cpp.o
[142/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/multisignalmapper.cpp.o
[143/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/methodargumentmodel.cpp.o
[144/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectclassinfomodel.cpp.o
[145/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o
FAILED: core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o 
/usr/bin/c++ -DBACKWARD_HAS_BACKTRACE=0 -DBACKWARD_HAS_BACKTRACE_SYMBOL=0 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=1 -DBACKWARD_HAS_DWARF=0 -DBACKWARD_HAS_LIBUNWIND=0 -DBACKWARD_HAS_UNWIND=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050500 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -Dgammaray_core_EXPORTS -I/home/yifan/packages/GammaRay/build/core -I/home/yifan/packages/GammaRay/core -I/home/yifan/packages/GammaRay/build/core/gammaray_core_autogen/include -I/home/yifan/packages/GammaRay -I/home/yifan/packages/GammaRay/3rdparty -I/home/yifan/packages/GammaRay/build -I/home/yifan/packages/GammaRay/3rdparty/qt/5.5 -I/home/yifan/packages/GammaRay/build/common -isystem /home/yifan/packages/GammaRay/3rdparty/backward-cpp -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtCore/6.7.0 -isystem /usr/include/qt6/QtCore/6.7.0/QtCore -isystem /usr/include/qt6/QtGui/6.7.0 -isystem /usr/include/qt6/QtGui/6.7.0/QtGui -isystem /usr/include/qt6/QtGui -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wsuggest-override -Wall -Wextra -pedantic -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -fno-operator-names -Wzero-as-null-pointer-constant -g -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -mno-direct-extern-access -MD -MT core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o -MF core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o.d -o core/CMakeFiles/gammaray_core.dir/metaobjectrepository.cpp.o -c /home/yifan/packages/GammaRay/core/metaobjectrepository.cpp
In file included from /home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:14:
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp: In static member function ‘static void GammaRay::MetaObjectRepository::initQObjectTypes()’:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: error: no matching function for call to ‘makeProperty(const char [9], QTimeZone (QDateTime::*)() const, void (QDateTime::*)(const QTimeZone&, QDateTime::TransitionResolution))’
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
In file included from /home/yifan/packages/GammaRay/core/metaobject.h:19,
                 from /home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:15:
/home/yifan/packages/GammaRay/core/metaproperty.h:233:22: note: candidate: ‘template<class Class, class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, GetterReturnType (Class::*)() const, void (Class::*)(typename GammaRay::detail::strip_const_ref<GetterReturnType>::type))’
  233 | inline MetaProperty *makeProperty(const char *name, GetterReturnType (Class::*getter)() const, void (Class::*setter)(typename detail::strip_const_ref<GetterReturnType>::type))
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:233:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   candidate expects 2 arguments, 3 provided
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:239:22: note: candidate: ‘template<class Class, class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, GetterReturnType (Class::*)() const, void (Class::*)(typename GammaRay::detail::add_const_ref<GetterReturnType>::type))’
  239 | inline MetaProperty *makeProperty(const char *name, GetterReturnType (Class::*getter)() const, void (Class::*setter)(typename detail::add_const_ref<GetterReturnType>::type))
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:239:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   candidate expects 2 arguments, 3 provided
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:246:22: note: candidate: ‘template<class Class, class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, GetterReturnType (Class::*)() const)’
  246 | inline MetaProperty *makeProperty(const char *name, GetterReturnType (Class::*getter)() const)
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:246:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   candidate expects 2 arguments, 3 provided
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:252:22: note: candidate: ‘template<class Class, class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, GetterReturnType (Class::*)() const noexcept)’
  252 | inline MetaProperty *makeProperty(const char *name, GetterReturnType (Class::*getter)() const noexcept)
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:252:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   mismatched types ‘GetterReturnType (Class::)() const noexcept’ and ‘QTimeZone (QDateTime::)() const’
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:266:22: note: candidate: ‘template<class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, GetterReturnType (*)())’
  266 | inline MetaProperty *makeProperty(const char *name, GetterReturnType (*getter)())
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:266:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   mismatched types ‘GetterReturnType (*)()’ and ‘QTimeZone (QDateTime::*)() const’
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:272:22: note: candidate: ‘template<class Class, class ValueType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, ValueType Class::*)’
  272 | inline MetaProperty *makeProperty(const char *name, ValueType Class::*member)
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:272:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   candidate expects 2 arguments, 3 provided
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:279:22: note: candidate: ‘template<class Class, class GetterReturnType> GammaRay::MetaProperty* GammaRay::MetaPropertyFactory::makeProperty(const char*, const std::function<ValueType(Class*)>&)’
  279 | inline MetaProperty *makeProperty(const char *name, const std::function<GetterReturnType(Class *)> &func)
      |                      ^~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaproperty.h:279:22: note:   template argument deduction/substitution failed:
/home/yifan/packages/GammaRay/core/metaobjectrepository.h:133:64: note:   mismatched types ‘const std::function<ValueType(Class*)>’ and ‘QTimeZone (QDateTime::*)() const’
  133 |     mo->addProperty(GammaRay::MetaPropertyFactory::makeProperty(#Getter, &Class::Getter, &Class::Setter));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yifan/packages/GammaRay/core/metaobjectrepository.cpp:138:5: note: in expansion of macro ‘MO_ADD_PROPERTY’
  138 |     MO_ADD_PROPERTY(QDateTime, timeZone, setTimeZone);
      |     ^~~~~~~~~~~~~~~
[146/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectdataprovider.cpp.o
[147/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectenummodel.cpp.o
[148/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/metaobjectregistry.cpp.o
[149/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectinstance.cpp.o
[150/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectlistmodel.cpp.o
[151/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/objectmethodmodel.cpp.o
[152/1111] Building CXX object core/CMakeFiles/gammaray_core.dir/gammaray_core_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
```
</details>

### PR DESCRIPTION
**Pull request by mattkdab**
This change enables building with Qt 6.7, but assuming [this Qt patch](https://codereview.qt-project.org/c/qt/qtbase/+/531661) is approved, the following will no longer be needed:

```diff
+ #if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
    MO_ADD_METAOBJECT1(QDeferredDeleteEvent, QEvent);
    MO_ADD_PROPERTY_RO(QDeferredDeleteEvent, loopLevel);
+ #endif
```

So while this works for now, it should not be the real final solution.

Eventually fixes #918

### CODE REVIEW

**Comment by winterz** [comment]
this is hard to verify until we add qt 6.7 to the CI matrix

@dantti

**Comment by dantti** [comment]
With the current 6.7 beta that Qt company released it still fails:
https://github.com/KDAB/GammaRay/actions/runs/7550206827/job/20555459025

**Comment by mattkdab** [comment]
If the patch at <https://codereview.qt-project.org/c/qt/qtbase/+/531661> is merged, it should enable the reversion of this part of the change:

```diff
+ #if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
    MO_ADD_METAOBJECT1(QDeferredDeleteEvent, QEvent);
    MO_ADD_PROPERTY_RO(QDeferredDeleteEvent, loopLevel);
+ #endif
```

@redstrate has already tested this

**Comment by mattkdab** [comment]
> With the current 6.7 beta that Qt company released it still fails: https://github.com/KDAB/GammaRay/actions/runs/7550206827/job/20555459025

It should pass for this PR only at this point

**Review by winterz — APPROVED** [review]

**Pull request merged**
