### PR TITLE
Enable Werror on CI

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
```
/usr/bin/c++ -DHAVE_STRING_H=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050400 -DQT_DISABLE_DEPRECATED_BEFORE=0x050500
```

Not sure where `DQT_DISABLE_DEPRECATED_BEFORE=0x050400` comes from

**Comment by Waqar144** [comment]
> ```
> /usr/bin/c++ -DHAVE_STRING_H=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050400 -DQT_DISABLE_DEPRECATED_BEFORE=0x050500
> ```
> 
> Not sure where `DQT_DISABLE_DEPRECATED_BEFORE=0x050400` comes from

Was coming from 3rdparty/KDSME. I have now disabled Gammaray's define so that KDSME's defaults are honored.

**Comment by Waqar144** [comment]
Nightly is still without Werror. Will try to enable it there and with clang-tidy as well.

**Comment by winterz** [comment]
+2
you can ignore the failure due to missing kdstatemachineeditor.
that's something @dantti probably needs to fix

**Pull request merged**
