### PR TITLE
Fix coding style

### PR DESCRIPTION
**Pull request by krf**

### CODE REVIEW

**Comment by winterz** [comment]
compiles and the tests are ok.
I wonder if you can also enforce line length of 100 chars ?

**Comment by krf** [comment]
@vkrause: Needs rebase -- but generally: Are you fine with this change? Any additions to the coding style rules needed?

**Comment by krf** [comment]
Reran my scripts, updated the commit message. Unit tests still work.

**Comment by vkrause** [comment]
qt3dgeometryextensioninterface.cpp looks messed up, the rest is ok I think, so with that fixed this can go in.

**Comment by krf** [comment]
I fixed *qt3dgeometryextensioninterface.cpp*, for what it's worth. Uncrustify messed that up indeed. Thanks for the hint.

**Pull request closed without merging**
