### PR TITLE
Open qrc navigation in our Resource Inspector.

### PR DESCRIPTION
**Pull request by pasnox**
Task-Id: KDEND-40

### CODE REVIEW

**Comment by akreuzkamp** [comment]
qrc code navigation currently only works with QtCreator (or theoretically with any ide, that supports it). Your idea is good, but it breaks the qrc code navigation in QtCreator, where we definitely want to navigate to the editor, doesn't it? I guess we'd need some way for the qtc-gammaray-plugin to change that behavior.

**Comment by pasnox** [comment]
If I recall, now QtC does not longer use the client MainWindow ?
So we can write our own handler.
If not then maybe we can rework a bit the api to add a virtual member somewhere.

**Comment by akreuzkamp** [comment]
you're right, sorry. QtC never used MainWindow::navigateToCode(), so this patch doesn't in any way interfere with code navigation in QtC.

**Comment by vkrause** [comment]
+2

**Comment by vkrause** [comment]
Integrated into master.

**Pull request closed without merging**
